const FILE_NAMES = {
  INDEX: 'index.js',
  STYLES: 'index.styles.js',
  UTILS: 'index.utils.js',
  CONSTANTS: 'index.constants.js',
  TYPES: 'index.types.js'
}

const FILE_STRUCTURE_CHOICES = {
  DEFAULT: 'Default',
  DEFAULT_WITHOUT_TYPES: 'Default with out types',
  QUICK_START: 'Quick start',
  QUICK_START_WITHOUT_TYPES: 'Quick start without types',
  CUSTOM: 'Custom'
}

const FILE_STRUCTURE_CHOICE_TITLES = {
  [FILE_STRUCTURE_CHOICES.DEFAULT]: 'Default - [index.js, styles, utils, constants, types]',
  [FILE_STRUCTURE_CHOICES.DEFAULT_WITHOUT_TYPES]: 'Default with out types - [index.js, styles, utils, constants]',
  [FILE_STRUCTURE_CHOICES.QUICK_START]: 'Quick start - [index.js, styles, types]',
  [FILE_STRUCTURE_CHOICES.QUICK_START_WITHOUT_TYPES]: 'Quick start without types - [index.js, styles]',
  [FILE_STRUCTURE_CHOICES.CUSTOM]: FILE_STRUCTURE_CHOICES.CUSTOM
}

const FILE_STRUCTURE_FILES = {
  [FILE_STRUCTURE_CHOICES.DEFAULT]: Object.values(FILE_NAMES),
  [FILE_STRUCTURE_CHOICES.DEFAULT_WITHOUT_TYPES]: [FILE_NAMES.INDEX, FILE_NAMES.STYLES, FILE_NAMES.UTILS, FILE_NAMES.CONSTANTS],
  [FILE_STRUCTURE_CHOICES.QUICK_START]: [FILE_NAMES.INDEX, FILE_NAMES.STYLES],
  [FILE_STRUCTURE_CHOICES.QUICK_START_WITHOUT_TYPES]: [FILE_NAMES.INDEX, FILE_NAMES.STYLES, FILE_NAMES.TYPES],
  [FILE_STRUCTURE_CHOICES.CUSTOM]: Object.values(FILE_NAMES),
}

const FILE_NAME_TO_EJS_TEMPLATE_FILE_MAP = {
  [FILE_NAMES.INDEX]: 'index.ejs',
  [FILE_NAMES.STYLES]: 'index.styles.ejs',
  [FILE_NAMES.UTILS]: 'index.utils.ejs',
  [FILE_NAMES.CONSTANTS]: 'index.constants.ejs',
  [FILE_NAMES.TYPES]: 'index.types.ejs',
}

const FILE_STRUCTURE_CHOICE_TYPE_SAFETY = {
  [FILE_STRUCTURE_CHOICES.DEFAULT]: true,
  [FILE_STRUCTURE_CHOICES.DEFAULT_WITHOUT_TYPES]: false,
  [FILE_STRUCTURE_CHOICES.QUICK_START]: true,
  [FILE_STRUCTURE_CHOICES.QUICK_START_WITHOUT_TYPES]: false,
  // let's say by default it's true
  [FILE_STRUCTURE_CHOICES.CUSTOM]: true,
}


module.exports = {
  FILE_NAMES,
  FILE_STRUCTURE_CHOICES,
  FILE_STRUCTURE_FILES,
  FILE_STRUCTURE_CHOICE_TITLES,
  FILE_STRUCTURE_CHOICE_TYPE_SAFETY,
  FILE_NAME_TO_EJS_TEMPLATE_FILE_MAP,
}
